apiVersion: v1
kind: Pod
metadata:
  name: test-07
  labels:
    app: a1
    zone: z1
spec:
  containers:
  - name: main6
    image: busybox:latest
    command: ['sh', '-c', 'top -b']
    resources:
      limits:
        caster.io/colocation-cpu: 1
      requests:
        caster.io/colocation-cpu: 1

