apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    env: test
spec:
  shareProcessNamespace: true
  containers:
  - name: main
    image: hub.c.163.com/public/centos:6.7-tools
    command: ["bash","-c","python2 -m SimpleHTTPServer 8080"]
    resources:
      limits:
        cpu: 102m
        memory: 102Mi
      requests:
        cpu: 101m
        memory: 101Mi
