apiVersion: v1
kind: Pod
metadata:
  name: centos3
  labels:
    env: test
spec:
  #dnsPolicy: Default
  shareProcessNamespace: true
  containers:
  - name: main
    image: hub.c.163.com/public/centos:6.7-tools
    command: ["bash","-c","python2 -m SimpleHTTPServer 8080 && sleep 100121212121122222sadasdasdasdwwasdasdsadasdasdadsadsasdasdasdasdadasaawqweqdasjdasjkjkhadsjkhdsahhas100121212121122222sadasdasdasdwwasdasdsadasdasdadsadsasdasdasdasdadasaawqweqdasjdasjkjkhadsjkhdsahhas"]
    resources:
        limits:
           cpu: "1000m"
           memory: "1Gi"
        requests:
           cpu: "1000m"
           memory: "1Gi"
