apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-ss
spec:
  selector:
    matchLabels:
      app: nginx-ss
  replicas: 3
  serviceName: nginx-ss
  template:
    metadata:
     labels:
       app: nginx-ss
    spec:
      containers:
      - name: nginx-ss
        image: nginx:1.14.2

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ss
  labels:
    app: nginx-ss
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-ss
